service: earbleed
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  httpApi:
    cors: true

functions:
  process_audio:
    handler: handler.process_audio
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline
